#!/bin/bash

# A simple script that installs a topology file to the desvirt directory
# Author: Michael Conard

if [ -z "$RIOTBASE" ]
then
    echo "RIOTBASE environment variable not defined"
    exit 1
fi

if [ -z "$1" ] 
then
    echo "Filename argument not supplied"
    exit 1
fi

mv $1 ${RIOTBASE}/dist/tools/desvirt/desvirt/.desvirt/$1
echo "$1 has been installed for desvirt to use"

