#!/bin/bash

// Manually edit the TOPO and PROJ names to reflect your project
// This script will cleanup your last RIOT instance AND launch
// a new one

TOPO=bi-ring5
PROJ=my_project

./${TOPO}_cleanup.sh ${PROJ}
./${TOPO}_cleanup.sh master_node

make all

./riot define ${TOPO}
./riot start ${TOPO}

