#!/bin/bash

// Manually edit the TOPO and PROJ names to reflect your project
// This script will cleanup your last RIOT instance AND launch
// a new one

TOPO=mesh12-3x4
PROJ=my_project

./${TOPO}_cleanup.sh ${PROJ}

make all

./riot define ${TOPO}
./riot start ${TOPO}

